"""Increased hash to 170

Revision ID: 4144a2e51ac6
Revises: fdde17ea4822
Create Date: 2023-12-28 18:51:44.983023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4144a2e51ac6'
down_revision = 'fdde17ea4822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=170),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=170),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###
